name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
      - uses: actions/checkout@v2

      - name: Deploy to heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'react-nest-postgresql-example'
          heroku_email: 'luka.mat99@gmail.com'
