name: Run Server Tests

on:
  pull_request:
    branches: [master, development]
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci './server'

      - name: Lint code
        run: npm run lint './server'

      - name: Run tests
        run: npm run test './server'
